"""Add default value to close date

Revision ID: 40fa0fde4c5c
Revises: 2c8e8cd2138a
Create Date: 2023-12-16 21:41:32.980125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fa0fde4c5c'
down_revision = '2c8e8cd2138a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
